services:
  vnc:
    build: .
    hostname: dubiandubaian
    volumes:
      - dubian_data:/home/dubian
    ports:
      - "8444:8444"
    privileged: true
    stdin_open: true
    tty: true

volumes:
  dubian_data
