services:
  vnc:
    build: .
    hostname: debaian
    volumes:
      - debaian_data:/home/debaian
    ports:
      - "8444:8444"
    privileged: true
    stdin_open: true
    tty: true

volumes:
  debaian_data:
